/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TugasP9;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dimas
 */
public class AppMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form AppMahasiswa
     */
    public AppMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        textNIM = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        textMatkul = new javax.swing.JTextField();
        textNilai1 = new javax.swing.JTextField();
        textNilai2 = new javax.swing.JTextField();
        textNilai3 = new javax.swing.JTextField();
        textNilai4 = new javax.swing.JTextField();
        textNilai5 = new javax.swing.JTextField();
        textNilaiAkhir = new javax.swing.JTextField();
        bttnSimpan = new javax.swing.JButton();
        bttnHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();

        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        textNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNIMActionPerformed(evt);
            }
        });

        textAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAlamatActionPerformed(evt);
            }
        });

        textNilaiAkhir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textNilaiAkhirMouseClicked(evt);
            }
        });
        textNilaiAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNilaiAkhirActionPerformed(evt);
            }
        });

        bttnSimpan.setText("Simpan");
        bttnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSimpanActionPerformed(evt);
            }
        });

        bttnHapus.setText("Hapus");
        bttnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnHapusActionPerformed(evt);
            }
        });

        jLabel1.setText("NIM");

        jLabel2.setText("Mata Kuliah");

        jLabel3.setText("Alamat");

        jLabel4.setText("Nama");

        jLabel5.setText("Nilai 1 [10%]");

        jLabel6.setText("Nilai 2 [15%]");

        jLabel7.setText("Nilai 3 - UTS [25%]");

        jLabel8.setText("Nilai 4 [15%]");

        jLabel9.setText("Nilai 5 [35%]");

        jLabel10.setText("Nilai Akhir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnSimpan)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(textNama)
                            .addComponent(textAlamat)
                            .addComponent(textMatkul)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(bttnHapus)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(66, 66, 66))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNilai5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNilaiAkhir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNilai1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNilai2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNilai3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNilai4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNilai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNilai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNilai3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNilai4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNilai5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnSimpan)
                            .addComponent(bttnHapus))
                        .addGap(34, 34, 34))))
        );

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Alamat", "Mata Kuliah", "Nilai AKhir"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNIMActionPerformed
    
    private void hitungNilaiAkhir() {
    try {
        // Mengambil nilai dari text field, gunakan nilai 0 jika kosong
        double nilai1 = textNilai1.getText().isEmpty() ? 0 : Double.parseDouble(textNilai1.getText());
        double nilai2 = textNilai2.getText().isEmpty() ? 0 : Double.parseDouble(textNilai2.getText());
        double nilai3 = textNilai3.getText().isEmpty() ? 0 : Double.parseDouble(textNilai3.getText());
        double nilai4 = textNilai4.getText().isEmpty() ? 0 : Double.parseDouble(textNilai4.getText());
        double nilai5 = textNilai5.getText().isEmpty() ? 0 : Double.parseDouble(textNilai5.getText());
        

        // Hitung nilai akhir (misal, 30% tugas, 30% UTS, 40% UAS)
        double nilaiAkhir = (0.1 * nilai1) + (0.15 * nilai2) + (0.25 * nilai3) + (0.15 * nilai4) + (0.35 * nilai5);

        // Tampilkan nilai akhir di text field
        textNilaiAkhir.setText(String.format("%.2f", nilaiAkhir));
    } catch (NumberFormatException ex) {
        // Tangani jika input bukan angka
        textNilaiAkhir.setText("Error");
    }
}
    
    private void bttnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSimpanActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableData.getModel();
        try {
            String nim = textNIM.getText();
            String nama = textNama.getText();
            String alamat = textAlamat.getText();
            String mataKuliah = textMatkul.getText();
            
            textNilai1.getDocument().addDocumentListener(new DocumentListener() {
                public void insertUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
                public void removeUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
                public void changedUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
            });
            
            textNilai2.getDocument().addDocumentListener(new DocumentListener() {
                public void insertUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
                public void removeUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
                public void changedUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
            });
            
            textNilai3.getDocument().addDocumentListener(new DocumentListener() {
                public void insertUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
                public void removeUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
                public void changedUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
            });
            
            textNilai4.getDocument().addDocumentListener(new DocumentListener() {
                public void insertUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
                public void removeUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
                public void changedUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
            });
            
            textNilai5.getDocument().addDocumentListener(new DocumentListener() {
                public void insertUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
                public void removeUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
                public void changedUpdate(DocumentEvent e) { hitungNilaiAkhir(); }
            });
            
            // Ambil nilai dan hitung nilai akhir
            double nilai1 = Double.parseDouble(textNilai1.getText()) * 0.1;
            double nilai2 = Double.parseDouble(textNilai2.getText()) * 0.15;
            double nilai3 = Double.parseDouble(textNilai3.getText()) * 0.25;
            double nilai4 = Double.parseDouble(textNilai4.getText()) * 0.15;
            double nilai5 = Double.parseDouble(textNilai5.getText()) * 0.35;

            double nilaiAkhir = nilai1 + nilai2 + nilai3 + nilai4 + nilai5;
            hitungNilaiAkhir();

            // Tambah data ke tabel
            model.addRow(new Object[]{nim, nama, alamat, mataKuliah, nilaiAkhir});

            // Bersihkan input
            bersihkanInput();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan nilai dengan benar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnSimpanActionPerformed

    private void textAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAlamatActionPerformed
    
    private void textNilaiAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNilaiAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNilaiAkhirActionPerformed

    private void bttnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnHapusActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableData.getModel();
        int selectedRow = tableData.getSelectedRow();
        if (selectedRow != -1) {
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus.", "Hapus Data", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bttnHapusActionPerformed

    private void textNilaiAkhirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNilaiAkhirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textNilaiAkhirMouseClicked
    
    private void bersihkanInput() {
        textNIM.setText("");
        textNama.setText("");
        textAlamat.setText("");
        textMatkul.setText("");
        textNilai1.setText("");
        textNilai2.setText("");
        textNilai3.setText("");
        textNilai4.setText("");
        textNilai5.setText("");
        textNilaiAkhir.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnHapus;
    private javax.swing.JButton bttnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textMatkul;
    private javax.swing.JTextField textNIM;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNilai1;
    private javax.swing.JTextField textNilai2;
    private javax.swing.JTextField textNilai3;
    private javax.swing.JTextField textNilai4;
    private javax.swing.JTextField textNilai5;
    private javax.swing.JTextField textNilaiAkhir;
    // End of variables declaration//GEN-END:variables
}
